

str = '  ---------------------------------------------------------------------------------- \n'
str += '|               Thank you for your attention to our FOCUS model                    |\n'
str += '|               -----------------------------------------------                    |\n'
str += '|               -----------------------------------------------                    |\n'
str += '| In this docker container, we provide our source code and pre-trained models.     |\n'
str += '| This docker container follows the same license as in:                            |\n'
str += '|         *     https://github.com/unibas-gravis/Occlusion-Robust-MoFA.    *       |\n'
str += '  ---------------------------------------------------------------------------------- \n'
str += '  ---------------------------------------------------------------------------------- \n'
str += '|                                 Instructions                                     |\n'
str += '| 1. Prepare data                                                                  |\n'
str += '|                                                                                  |\n'
str += '|    1) Prepare .csv files for the training set, validation set, and testing set.  |\n'
str += '|       The .csv files should contain rows of [filename + 68 landmark coordinates].|\n'
str += '|    We recommend using the 68 2D landmarks detected by 2D-and-3D-face-alignment.  |\n'
str += "|    Please name the target image as 'image_name.jpg' and GT masks as              |\n"
str += "|    'image_name_visible_skin_mask.png'.                                           |\n"
str += '|    2) The image directory should follow the structure below:                     |\n'
str += '|                                                                                  |\n'
str += '|    ./image_root                                                                  |\n'
str += '|    ├── Dataset                     # Folder containing the images                |\n'
str += '|        ├──1.jpg                    # Target image             |\n'
str += '|        ├──1_visible_skin_mask.png  # GT masks for testing. (optional for training)|\n'
str += '|        └──...                                                                    |\n'
str += '|    ├── train_landmarks.csv      # .csv file for the train set.                   |\n'
str += '|    ├── test_landmarks.csv       # .csv file for the test set.                    |\n'
str += '|    ├── val_landmarks.csv        # .csv file for the validation set.              |\n'
str += '|    └── all_landmarks.csv        # .csv file for the whole dataset. (optional)    |\n'
str += '|                                                                                  |\n'
str += '| 2. Test on your own data                                                         |\n'
str += '|                                                                                  |\n'
str += "|  python Demo.py --img_path ./image_root --pretrained_model_test './pretrained.model'\n"
str += '|                                                                                  |\n'
str += '|  The following arguments are optional:                                           |\n'
str += '|      --output_path      [default:./reconstructed_imgs]                           |\n'
str += '|      --batch_size       [default:12]                                             |\n'
str += '|      --gpu              [default:0]   GPU ID                                     |\n'
str += '|                                                                                  |\n'
str += '|  We provide models trained for the Celeb A HQ dataset at:                        |\n'
str += '|         ./MoFA_UNet_Save/MoFA_UNet_CelebAHQ/unet_200000.model                    |\n'
str += '|        ./MoFA_UNet_Save/MoFA_UNet_CelebAHQ/enc_net_200000.model                  |\n'
str += '|                                                                                  |\n'
str += '|  and models trained for the NoW Challenge at:                                    |\n'
str += '|          ./MoFA_UNet_Save/For_NoW_Challenge/unet_210000.model                    |\n'
str += '|         ./MoFA_UNet_Save/For_NoW_Challenge/enc_net_210000.model                  |\n'
str += '|                                                                                  |\n'
str += '|  3. Adapt to your own model                                                      |\n'
str += '|                                                                                  |\n'
str += "|  python Step5_Fit_to_other_dataset.py --pretrained_model iteration_value --img_path ./image_root --output_name your_pipeline_name\n"
str += '|                                                                                  |\n'
str += '|  NOTE that --pretrained_model stands for the iteration of the pre-trained model. |\n'
str += '|  By default, the models for the Celeb A HQ dataset are used as a start point.    |\n'
str += '|  The following arguments are optional:                                           |\n'
str += '|      --output_name      [default:MoFA_UNet_Adaptedto_Dataset]                    |\n'
str += '|      --pretrained_model [default:0]                                              |\n'
str += '|      --batch_size       [default:12]                                             |\n'
str += '|      --learning_rate    [default:0.1]                                            |\n'
str += '|      --epochs           [default:130]                                            |\n'
str += '|      --gpu              [default:0]   GPU ID                                     |\n'
str += '|                                                                                  |\n'
str += '|                                                                                  |\n'
str += '|                                                                                  |\n'
str += '|                                                                                  |\n'
str += '|  If there is any problem, contact zxcv8747@126.com or chunlulilisa@gmail.com     |\n'
str += '|                                                                                  |\n'
str += '  ---------------------------------------------------------------------------------- \n'




print(str)
